backend:
  name: github
  branch: master
  repo: sschottler/progatsby2

media_folder: static/img
public_folder: /img

collections:
  - name: 'Team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
